outfiles:
  - 'test.hmr'
  - 'test.bsrate'
  - 'test.hypermr'
  - 'test.levels'
  - 'test.pmd'
  - 'test.amr'

genome_fasta_file: '/home/sena/code/methpipe/abismal/genome.fa'
paired: True
cpg_only: True

