name: DNMTools builds on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get install -y libhts-dev libgsl-dev
    - name: Generate configure script
      run: ./autogen.sh
    - name: Configure for g++
      run: ./configure CXX="g++"
    - name: Build with g++
      run: make
    - name: Test the g++ build
      run: make check-TESTS
    - name: Cleanup after the g++ build
      run: make distclean
    - name: Install Clang/LLVM dependencies
      run: sudo apt-get install -y libomp-dev
    - name: Configure for clang++
      run: ./configure CXX="clang++"
    - name: Build with clang++
      run: make
    - name: Test the clang++ build
      run: make
    - name: Cleanup after the clang++ build
      run: make distclean
